ModelName: face_yolo
SavedAs: frozen
InputWidth: 288
InputHeight: 288

InputNames:
  - img
  - training

OutputNames:
  - prob
  - x_center
  - y_center
  - w
  - h

Architecture: face_yolo
WriteNodes: True
RosBag: ../bags/bag3.bag

OptimParams:
  Formats:
    - FP32
    - FP16
    - INT8
  MSS:
    - 3
    - 20
    - 50
  MCE:
    - 1
    - 3
    - 5
  AllowGrowth: True
