ModelName: face_corrector
SavedAs: frozen
InputWidth: 50
InputHeight: 50

InputNames:
  - img
  - training

OutputNames:
  - X
  - Y
  - W
  - H

Architecture: face_corrector
WriteNodes: True
RosBag: ../bags/bag3.bag

OptimParams:
  Formats:
    - FP32
    - FP16
    - INT8
  MSS:
    - 3
    - 20
    - 50
  MCE:
    - 1
    - 3
    - 5
  AllowGrowth: True
