ModelName: ssd_mobilenet_v2_coco
SavedAs: checkpoint
InputWidth: 300
InputHeight: 300

InputNames:
  - image_tensor

OutputNames:
  - detection_boxes
  - detection_scores
  - detection_classes
  - num_detections

Architecture: ssd
WriteNodes: True

OptimParams:
  Formats:
    - FP32
    - FP16
  MSS:
    - 3
    - 20
    - 50
  MCE:
    - 1
    - 3
    - 5
  AllowGrowth: True
