ModelName: yolov3_tiny_coco
SavedAs: frozen
InputWidth: 416
InputHeight: 416

InputNames:
  - inputs

OutputNames:
  - output_boxes

Architecture: yolov3tiny
WriteNodes: True
RosBag: ../bags/bag3.bag

OptimParams:
  Formats:
    - FP32
    - FP16
    - INT8
  MSS:
    - 3
    - 20
    - 50
  MCE:
    - 1
    - 3
    - 5
  AllowGrowth: True


