ModelName: yolov3_coco
SavedAs: frozen
InputWidth: 416
InputHeight: 416

InputNames:
  - input/input_data

OutputNames:
  - pred_sbbox/concat_2
  - pred_mbbox/concat_2
  - pred_lbbox/concat_2

Architecture: yolov3
WriteNodes: True

OptimParams:
  Formats:
    - FP32
    - FP16
  MSS:
    - 3
    - 20
    - 50
  MCE:
    - 1
    - 3
    - 5
  AllowGrowth: True


