ModelName: facenet_inception_resnet_vggface2
SavedAs: frozen
InputWidth: 160
InputHeight: 160

InputNames:
  - input
  - phase_train

OutputNames:
  - embeddings

Architecture: ssd
WriteNodes: True

OptimParams:
  Formats:
    - FP32
    - FP16
  MSS:
    - 3
    - 20
    - 50
  MCE:
    - 1
    - 3
    - 5
  AllowGrowth: True
