NodeName: "followperson"
Mode: "benchmark"
RosbagFile: "bags/bag3.bag"
LogDir: "logs/benchmarks"
DisplayImages: false
Networks:
  Arch: yolov3tiny
  DetectionModel: "Optimization/dl_models/yolov3_tiny_coco/optimizations/FP16_3_3.pb"
  DetectionWidth: 416
  DetectionHeight: 416
  FaceEncoderModel: "Optimization/dl_models/facenet_inception_resnet_vggface2/optimizations/FP32_3_3.pb"

RefFace: "resources/ref_face/refface.jpg"

Topics:
  RGB: "/camera/rgb/image_raw"
  Depth: "/camera/depth_registered/image_raw"
  Motors: "/mobile_base/commands/velocity"
