NodeName: "followperson"
Mode: "inference"
DisplayImages: true
Networks:
  Arch: ssd
  DetectionModel: "optim/dl_models/ssd_mobilenet_v1_0.75_depth_coco/optimizations/FP16_50_1.pb"
  DetectionWidth: 300
  DetectionHeight: 300
  FaceEncoderModel: "optim/dl_models/facenet_inception_resnet_vggface2/optimizations/FP32_3_1.pb"

RefFace: "resources/ref_face/refface.jpg"

Topics:
  RGB: "/camera/rgb/image_raw"
  Depth: "/camera/depth_registered/image_raw"
  Motors: "/mobile_base/commands/velocity"
