FollowPerson:
  Device: kobuki

  Motors:
    Server: ROS # Deactivate, Ice, ROS
    Topic: "/mobile_base/commands/velocity"
    Name: kobukiMotors
    maxV: 3
    maxW: 0.7

  Camera:
    Server: ROS
    Topic: "/camera/rgb/image_raw"
    Name: cameraA
    Fps: 30

  Depth:
    Server: ROS
    Topic: "/camera/depth_registered/image_raw"
    Name: cameraB
    Fps: 30

  Network:
    Framework: TensorFlow  # Currently supported: "Keras" or "TensorFlow"
    #Model: VGG_512_512_coco.h5
    Model: ssdlite_mobilenet_v2_coco_2018_05_29.pb
    Dataset: COCO # available: VOC, COCO, KITTI, OID, PET
    SiameseModel: siamese_model.pb

  Mom:
    ImagePath: mom_img/sample_img.jpg

  NodeName: FollowPerson
