NodeName: "followperson"
Mode: "inference"
DisplayImages: true
Networks:
  DetectionModel: "optim/dl_models/ssd_mobilenet_v1_0.75_depth_coco/frozen_graph.pb"
  FaceEncoderModel: "optim/dl_models/facenet_inception_resnet_vggface2/frozen_graph.pb"

RefFace: "resources/ref_face/refface.jpg"

Topics:
  RGB: "/camera/rgb/image_raw"
  Depth: "/camera/depth_registered/image_raw"
  Motors: "/mobile_base/commands/velocity"
